using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum SoundsEnum
{
    AMBIENT = 0,
    HERO_ATTACK_HIT_1 = 1,
    HERO_ATTACK_HIT_2 = 2,
    HERO_ATTACK_HIT_3 = 3,
    HERO_DRINK_POTION = 4,
    HERO_IMPACT_ON_SHIELD = 5,
    HERO_INJURY_1 = 6,
    HERO_INJURY_2 = 30,
    HERO_INJURY_3 = 7,
    HERO_ATTACKMISS = 35,
    PICKUP_GEM = 8,
    PICKUP_GOLD = 9,
    VESSEL_BREAK_1 = 10,
    VESSEL_BREAK_2 = 11,
    VESSEL_BREAK_3 = 12,
    VESSEL_BREAK_4 = 13,
    FORGE_SHOP_TAB_SWITCH = 14,
    FORGE_ONCLICK_CLEAR = 15,
    FORGE_ONCLICK_HAMMER = 16,
    FORGE_FAILURE = 31,
    FORGE_SUCCESS = 32,
    GENERAL_CLICK_BUTTON_1 = 17,
    GENERAL_CLICK_BUTTON_2 = 18,
    GENERAL_DRAG_ITEM = 19,
    GENERAL_PICKUP_ITEM = 20,
    HUD_SKILL_TO_SLOT = 21,
    INVENTORY_GEM_TO_SLOT = 22,
    INVENTORY_CLOSE = 23,
    INVENTORY_OPEN = 33,
    INVENTORY_SKILLS_CLOSE = 24,
    INVENTORY_SKILLS_OPEN = 25,
    INVENTORY_SKILLS_RETURN_SKILL = 34,
    SHOP_INC_DEC = 26,
    SHOP_ON_BUY_SELL = 27,
    TUTORIAL_CLOSE = 28,
    TUTORIAL_OPEN = 29
    
}
